#!/bin/sh /etc/rc.common

START=99
STOP=10

USE_PROCD=1
PROG=/usr/sbin/schoolnet-auth

start_service() {
    local enabled
    config_load schoolnet
    config_get_bool enabled base enabled 0

    if [ "$enabled" -eq 1 ]; then
        procd_open_instance
        procd_set_param command "$PROG"
        procd_set_param stdout 1
        procd_set_param stderr 1
        # 设置重生（如果脚本挂了会自动重启）
        procd_set_param respawn
        procd_close_instance
    fi
}

service_triggers() {
    procd_add_reload_trigger "schoolnet"
}